apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boardgame
  name: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - image: jackdhub/:
        name: boardgame
